# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  user-service:
    build:
      target: dependencies  # Use dependencies stage for faster development
    volumes:
      - ./services/user-service:/app
      - pip_cache:/pip_cache
      # Mount source code for hot reloading
      - ./services/user-service/app:/app/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1  # Don't write .pyc files
      - PYTHONUNBUFFERED=1         # Force Python output to be unbuffered
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  recipe-service:
    build:
      target: dependencies
    volumes:
      - ./services/recipe-service:/app
      - pip_cache:/pip_cache
      - huggingface_cache:/root/.cache/huggingface
      - torch_cache:/root/.cache/torch
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_OFFLINE=0  # Allow model downloads in dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  meal-planner-service:
    build:
      target: dependencies
    volumes:
      - ./services/meal-planner-service:/app
      - pip_cache:/pip_cache
      - ./services/meal-planner-service/app:/app/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

  frontend:
    volumes:
      - ./frontend/src:/app/src  # Hot reload for frontend development
      - ./frontend/public:/app/public
    environment:
      - VITE_HMR_PORT=80  # Enable Vite hot module replacement